### ISSUE TITLE
Huge memory leaks

### ISSUE THREAD

**Issue by BohrShaw** [garyburd/go-explorer#13]
I encountered several huge memory leaks today when executing `:GeDoc pkg`, all leading to exhausting my system memory. But it's not reproducible yet. Am I the only one encountering this bug?

Environment:

- Ubuntu 14.04 x86_64
- golang 1.5/1.4
- Neovim compiled on Aug 28, obtained from the official PPA

**Comment by garyburd** [comment]
Please reopen this issue when you can provide information on how to reproduce the problem.
