### ISSUE TITLE
command for installing getool

### ISSUE THREAD

**Issue by akavel** [garyburd/go-explorer#2]
It'd be nice if there was a command which would `go get .../getool` (or `go get -u`?), similar as `:GoInstallBinaries` in vim-go.

**Comment by docwhat** [comment]
Unfortunately, `vim-go` stores its package list in an `s:packages` variable.

Maybe `vim-go` could detect `if exists('g:loaded_ge')` and automatically add `getool` or provide a way to add to the `s:packages` list somehow.

**Comment by garyburd** [comment]
Another fix is to merge go-explorer into vim-go.

**Comment by garyburd** [comment]
The go-explorer tool should be added to s:packages as part of the [integration of go-explorer with vim-go](https://github.com/fatih/vim-go/issues/361).
