### ISSUE TITLE
discover getool in $GOPATH even if not in $PATH

### ISSUE THREAD

**Issue by akavel** [garyburd/go-explorer#3]
e.g. [like it's done in vim-go](https://github.com/fatih/vim-go/blob/48125e61d8e8999a337b7e71a669a7d3b12a5e7f/autoload/go/oracle.vim#L100). Or at least provide a variable so that it could be configured to a specific path.

**Comment by garyburd** [comment]
Go Explorer now looks in $GOBIN and $GOPATH to find getool.

**Comment by akavel** [comment]
Works, thanks!
