### ISSUE TITLE
Allow showing/hiding private members

### ISSUE THREAD

**Issue by akavel** [garyburd/go-explorer#6]
It would be nice if there was a key which allowed to show/hide private members (funcs, vars, ...) in the godoc window (like the `?m=all` URL parameter in `godoc` -- see e.g.: http://golang.org/pkg/bytes/?m=all#makeSlice). (Technically, in Vim the `conceal` feature may possibly be of use here.)

**Comment by garyburd** [comment]
Conceal is not a solution for a couple of reasons. The default documentation view is not the same as the ?m=all view with some things hidden.  Conceal is not enabled in a commonly used version of Vim.

How about adding a command to toggle between default view and ?m=all view and a global variable that specifies the starting view when opening a documentation page?

**Comment by akavel** [comment]
Sure, if that's easier/better/more portable, then why not. For me the feature in itself would be what's important here. That'd really help me navigate my projects!

By the way, *huge* thanks especially for the folding feature, thanks to it I've already started being more inclined to `:GeDoc` the stdlib packages than to open the browser! (obviously, Ctrl-] jumping, paths tab-completion and local pkg name discovery are beyond awesome too, but folding seems to really have nailed it for me)

**Comment by akavel** [comment]
I've sent a pull request with implementation proposal.
