### ISSUE TITLE
'godoc' syntax definition conflicts with vim-go's syntax of same name

### ISSUE THREAD

**Issue by akavel** [garyburd/go-explorer#8]
I didn't even notice, only I was curious why folding isn't working, although mentioned in the recent commit.

Reordering the plugins in .vimrc (go-explorer first) worked for me, but I suppose many people may get bitten by this. I suppose renaming the syntax to "gedoc", or "gegodoc", or something could help, if you wouldn't mind?

**Comment by garyburd** [comment]
Fixed in 4ee735535fd7b059ee438c810ae50e8bf4fbdbb2.
